---
# tasks file for NginxCluster
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx status configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  template: src=status.conf dest=/etc/nginx/conf.d/status.conf
  template: src=server.conf dest=/etc/nginx/conf.d/server.conf

- name: insert firewalld rule for nginx
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: http service state
  service: name=nginx state=stopped enabled=no