---
# tasks file for NginxCluster
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx status configuration
  template: src=status.conf dest=/etc/nginx/conf.d/status.conf

- name: insert firewalld rule for nginx
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
