---
# tasks file for NginxCluster
- name: Install nginx
  yum: name=nginx state=present

- name: Template nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Template status.conf
  template: src=status.conf dest=/etc/nginx/default.d/status.conf

- name: Template server.conf
  template: src=server.conf dest=/etc/nginx/conf.d/server.conf

- name: Template tcpStream.conf
  when: tcp_streams is defined
  template: src=tcpStream.conf dest=/etc/nginx/tcpconf.d/tcpStream.conf
  #with_dict: "{{ tcp_streams }}"

- name: insert firewalld rule for nginx
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: http service state
  service: name=nginx state=stopped enabled=no