---
- name: Install NGINX Cluster
  hosts: nginx-cluster
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - nginx
    - pacemaker
  vars:
    tcp_streams:
      rdp_3389:
        listen_ip: 0.0.0.0
        listen_port: 3389
        proxy_bind: 192.168.1.231
        upstream_server:
          - ip: 192.168.1.111
            port: 3389
      dicom_104:
        listen_ip: 0.0.0.0
        listen_port: 104
        proxy_bind: 192.168.1.230
        upstream_servers:
          - ip: 192.168.1.211
            port: 104
          - ip: 192.168.1.214
            port: 104
    pacemaker_ansible_group: nginx-cluster
    pacemaker_password: secret
    pacemaker_cluster_name: nginx_ha_cluster
    pacemaker_properties:
      stonith_enabled: "false"
      no-quorum-policy: "ignore"
    pacemaker_resources_delete: true
    pacemaker_resources:
      - id: vip230
        type: "ocf:heartbeat:IPaddr2"
        options:
          ip: 192.168.1.230
          cidr_netmask: 24
        op:
          - action: monitor
            options:
              interval: 5s
        group:
          name: "web_services"
      - id: vip231
        type: "ocf:heartbeat:IPaddr2"
        options:
          ip: 192.168.1.231
          cidr_netmask: 24
        op:
          - action: monitor
            options:
              interval: 5s
        group:
          name: "web_services"
      - id: nginx
        type: "ocf:heartbeat:nginx"
        options:
          configfile: "/etc/nginx/nginx.conf"
          status10url: "http://localhost/nginx_status"
        op:
          - action: monitor
            options:
              interval: 5s
              start-delay: "5s"
        group:
          name: "web_services"
#    pacemaker_constraints:
#      - constraint: "colocation add nginx vip230 INFINITY"
#      - constraint: "order vip230 then nginx"