---
- name: Install NGINX Cluster
  hosts: nginx-cluster
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - nginx
    - pacemaker

  vars:
      pacemaker_ansible_group: cluster-nginx
      pacemaker_password: secret
      pacemaker_cluster_name: nginx_ha_cluster
      pacemaker_properties:
        stonith_enabled: "false"
      pacemaker_resources:
        - id: vip230
          type: "ocf:heartbeat:IPaddr2"
          options:
            ip: 192.168.1.230
            cidr_netmask: 24
          op:
            - action: monitor
              options:
                interval: 5s
        - id: nginx
          type: "ocf:heartbeat:nginx"
          configfile: "/etc/nginx/nginx.conf"
          statusurl: "http://localhost/nginx_status"
          op:
            - action: monitor
              options:
                interval: 5s
      pacemaker_constraints:
        - constraint: "colocation add nginx vip230 INFINITY"
        - constraint: "order vip230 then nginx"